version: '3.8'

services:
    frontend:
        build:
            context: .
        ports:
            - '3000:3000'
        networks:
            - app-network

    backend:
        build:
            context: ./api
        ports:
            - '5000:5000'
        depends_on:
            - postgres
        networks:
            - app-network
        environment:
            FLASK_SECRET_KEY: cheese
            DB_USER: postgres
            DB_PASS: abc
            DB_HOST: postgres
            DB_PORT: 5432
            DB_NAME: rep_db
        command:
            - /bin/sh
            - -c
            - |
                gunicorn -k eventlet --bind 0.0.0.0:5000 app:app
    postgres:
        image: postgres:15-alpine
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: rep_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: abc
            POSTGRES_HOST_AUTH_METHOD: trust
        networks:
            - app-network
        volumes:
            - postgres_data:/var/lib/postgresql/data

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
